DELIMITER $$
CREATE TRIGGER traslapeProgramacion
BEFORE INSERT ON SCHEDULE_
FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT *
        FROM SCHEDULE_
        WHERE ROOMID = NEW.ROOMID AND
              WEEKDAY = NEW.WEEKDAY AND (
              (NEW.STARTTIME >= STARTTIME AND NEW.ENDTIME <= ENDTIME) OR
              (NEW.STARTTIME <= STARTTIME AND NEW.ENDTIME >= ENDTIME) OR
              (NEW.STARTTIME <= STARTTIME AND NEW.ENDTIME > STARTTIME) OR
              (NEW.STARTTIME < ENDTIME AND NEW.ENDTIME >= ENDTIME)
              )
    ) THEN
        SIGNAL SQLSTATE '45000'SET MESSAGE_TEXT = 'La programacion se superpone con una programación existente.';
    END IF;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER traslapeReservaProgramacion
BEFORE INSERT ON RESERVATION
FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT *
        FROM SCHEDULE_
        WHERE ROOMID = NEW.ROOMID AND
              WEEKDAY = ((DAYOFWEEK(NEW.DATE_) - 2 + 7) % 7 + 1) AND (
              (NEW.STARTTIME >= STARTTIME AND NEW.ENDTIME <= ENDTIME) OR
              (NEW.STARTTIME <= STARTTIME AND NEW.ENDTIME >= ENDTIME) OR
              (NEW.STARTTIME <= STARTTIME AND NEW.ENDTIME > STARTTIME) OR
              (NEW.STARTTIME < ENDTIME AND NEW.ENDTIME >= ENDTIME)
              )
    ) THEN
        SIGNAL SQLSTATE '45000'SET MESSAGE_TEXT = 'La reserva se superpone con una programación existente.';
    END IF;
END$$
DELIMITER ;

DELIMITER $$
CREATE TRIGGER traslapeReservaReserva
BEFORE INSERT ON RESERVATION
FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT *
        FROM RESERVATION
        WHERE ROOMID = NEW.ROOMID AND
              Date_ = NEW.DATE_ AND (
              (NEW.STARTTIME >= STARTTIME AND NEW.ENDTIME <= ENDTIME) OR
              (NEW.STARTTIME <= STARTTIME AND NEW.ENDTIME >= ENDTIME) OR
              (NEW.STARTTIME <= STARTTIME AND NEW.ENDTIME > STARTTIME) OR
              (NEW.STARTTIME < ENDTIME AND NEW.ENDTIME >= ENDTIME)
              )
    ) THEN
        SIGNAL SQLSTATE '45000'SET MESSAGE_TEXT = 'La reserva se superpone con una reserva existente.';
    END IF;
END$$
DELIMITER ;


INSERT INTO RESERVATION(COURSEKEY,DATE_,STARTTIME,ENDTIME,NAME_,ROOMID,DURATION) 
VALUES('LIS-2082','2023-01-12','11:55:00','14:10:00','GOBEN','HU-106',85);

INSERT INTO SCHEDULE_(COURSEKEY,ROOMID, SECTION, WEEKDAY, STARTTIME, ENDTIME, SEMESTER, SEASON, YEAR_) 
VALUES ('LIS-2082','CN-109',4,1,'11:45:00','14:23:00',3,'PRIMAVERA',2023 );
 
 SELECT * FROM SCHEDULE_;
 SELECT * FROM RESERVATION;




